# Site settings
author: Cody Y
title: Binary Blather
header-img: img/home-bg.png
email: cyantis@gmail.com
copyright_name: Cody Y
description: > # this means to ignore newlines until "baseurl:"
  Some thoughts on web development and beyond.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cyantis

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
